window.CBCL_CONFIG = {
  appName: 'Break Wali League',
  dailyFreePlays: 5,
  billPattern: /^\d{4}\/\d{4}\/\d{4}$/,
  matchBoost: {
    startHour: 19,
    startMinute: 0,
    endHour: 23,
    endMinute: 30,
    multiplier: 2
  },
  scoring: {
    bowlingDisplay: {
      Bowled: 12,
      Catch: 8,
      LBW: 4,
      '-1': -1,
      '-4': -4,
      '-6': -6
    }
  },
  outcomes: {
    bat: [
      { label: '6', points: 6, weight: 10, type: 'positive', runs: 6, sixes: 1 },
      { label: '4', points: 4, weight: 20, type: 'positive', runs: 4 },
      { label: '3', points: 3, weight: 10, type: 'positive', runs: 3 },
      { label: '2', points: 2, weight: 20, type: 'positive', runs: 2 },
      { label: '1', points: 1, weight: 25, type: 'positive', runs: 1 },
      { label: 'Dot', points: 0, weight: 15, type: 'gold', dots: 1 }
    ],
    bowl: [
      { label: 'Bowled', points: 12, weight: 12, type: 'positive', wickets: 1 },
      { label: 'Catch', points: 8, weight: 16, type: 'positive', wickets: 1 },
      { label: 'LBW', points: 4, weight: 18, type: 'positive', wickets: 1 },
      { label: '-1', points: -1, weight: 20, type: 'negative' },
      { label: '-4', points: -4, weight: 20, type: 'negative' },
      { label: '-6', points: -6, weight: 14, type: 'negative' }
    ]
  },
  demoUsers: [
    {
      id: 'u1',
      name: 'Riya Sen',
      nickname: 'SkySix',
      phone: '9999999991',
      profilePhoto: '',
      totalPoints: 86,
      matchesPlayed: 17,
      runs: 58,
      wickets: 3,
      sixes: 7,
      dots: 4,
      streak: 4,
      playsToday: 2,
      lastPlayDate: '',
      history: []
    },
    {
      id: 'u2',
      name: 'Aman Das',
      nickname: 'YorkerYoddha',
      phone: '9999999992',
      profilePhoto: '',
      totalPoints: 74,
      matchesPlayed: 15,
      runs: 35,
      wickets: 5,
      sixes: 3,
      dots: 8,
      streak: 2,
      playsToday: 3,
      lastPlayDate: '',
      history: []
    },
    {
      id: 'u3',
      name: 'Sneha Roy',
      nickname: 'PowerPlay',
      phone: '9999999993',
      profilePhoto: '',
      totalPoints: 63,
      matchesPlayed: 14,
      runs: 44,
      wickets: 2,
      sixes: 5,
      dots: 5,
      streak: 5,
      playsToday: 1,
      lastPlayDate: '',
      history: []
    }
  ],
  iplMatches: [
    { num: 36, home: 'Rajasthan Royals',         away: 'Sunrisers Hyderabad',       date: '2026-04-25', time: '19:30', venue: 'Jaipur' },
    { num: 37, home: 'Chennai Super Kings',       away: 'Gujarat Titans',            date: '2026-04-26', time: '15:30', venue: 'Chennai' },
    { num: 38, home: 'Lucknow Super Giants',      away: 'Kolkata Knight Riders',     date: '2026-04-26', time: '19:30', venue: 'Lucknow' },
    { num: 39, home: 'Delhi Capitals',            away: 'Royal Challengers Bengaluru', date: '2026-04-27', time: '19:30', venue: 'Delhi' },
    { num: 40, home: 'Punjab Kings',              away: 'Rajasthan Royals',          date: '2026-04-28', time: '19:30', venue: 'New Chandigarh' },
    { num: 41, home: 'Mumbai Indians',            away: 'Sunrisers Hyderabad',       date: '2026-04-29', time: '19:30', venue: 'Mumbai' },
    { num: 42, home: 'Gujarat Titans',            away: 'Royal Challengers Bengaluru', date: '2026-04-30', time: '19:30', venue: 'Ahmedabad' },
    { num: 43, home: 'Rajasthan Royals',          away: 'Delhi Capitals',            date: '2026-05-01', time: '19:30', venue: 'Jaipur' },
    { num: 44, home: 'Chennai Super Kings',       away: 'Mumbai Indians',            date: '2026-05-02', time: '19:30', venue: 'Chennai' },
    { num: 45, home: 'Sunrisers Hyderabad',       away: 'Kolkata Knight Riders',     date: '2026-05-03', time: '15:30', venue: 'Hyderabad' },
    { num: 46, home: 'Gujarat Titans',            away: 'Punjab Kings',              date: '2026-05-03', time: '19:30', venue: 'Ahmedabad' },
    { num: 47, home: 'Mumbai Indians',            away: 'Lucknow Super Giants',      date: '2026-05-04', time: '19:30', venue: 'Mumbai' },
    { num: 48, home: 'Delhi Capitals',            away: 'Chennai Super Kings',       date: '2026-05-05', time: '19:30', venue: 'Delhi' },
    { num: 49, home: 'Sunrisers Hyderabad',       away: 'Punjab Kings',              date: '2026-05-06', time: '19:30', venue: 'Hyderabad' },
    { num: 50, home: 'Lucknow Super Giants',      away: 'Royal Challengers Bengaluru', date: '2026-05-07', time: '19:30', venue: 'Lucknow' },
    { num: 51, home: 'Delhi Capitals',            away: 'Kolkata Knight Riders',     date: '2026-05-08', time: '19:30', venue: 'Delhi' },
    { num: 52, home: 'Rajasthan Royals',          away: 'Gujarat Titans',            date: '2026-05-09', time: '19:30', venue: 'Jaipur' },
    { num: 53, home: 'Chennai Super Kings',       away: 'Lucknow Super Giants',      date: '2026-05-10', time: '15:30', venue: 'Chennai' },
    { num: 54, home: 'Royal Challengers Bengaluru', away: 'Mumbai Indians',          date: '2026-05-10', time: '19:30', venue: 'Raipur' },
    { num: 55, home: 'Punjab Kings',              away: 'Delhi Capitals',            date: '2026-05-11', time: '19:30', venue: 'Dharamshala' },
    { num: 56, home: 'Gujarat Titans',            away: 'Sunrisers Hyderabad',       date: '2026-05-12', time: '19:30', venue: 'Ahmedabad' },
    { num: 57, home: 'Royal Challengers Bengaluru', away: 'Kolkata Knight Riders',   date: '2026-05-13', time: '19:30', venue: 'Raipur' },
    { num: 58, home: 'Punjab Kings',              away: 'Mumbai Indians',            date: '2026-05-14', time: '19:30', venue: 'Dharamshala' },
    { num: 59, home: 'Lucknow Super Giants',      away: 'Chennai Super Kings',       date: '2026-05-15', time: '19:30', venue: 'Lucknow' },
    { num: 60, home: 'Kolkata Knight Riders',     away: 'Gujarat Titans',            date: '2026-05-16', time: '19:30', venue: 'Kolkata' },
    { num: 61, home: 'Punjab Kings',              away: 'Royal Challengers Bengaluru', date: '2026-05-17', time: '15:30', venue: 'Dharamshala' },
    { num: 62, home: 'Delhi Capitals',            away: 'Rajasthan Royals',          date: '2026-05-17', time: '19:30', venue: 'Delhi' },
    { num: 63, home: 'Chennai Super Kings',       away: 'Sunrisers Hyderabad',       date: '2026-05-18', time: '19:30', venue: 'Chennai' },
    { num: 64, home: 'Rajasthan Royals',          away: 'Lucknow Super Giants',      date: '2026-05-19', time: '19:30', venue: 'Jaipur' },
    { num: 65, home: 'Kolkata Knight Riders',     away: 'Mumbai Indians',            date: '2026-05-20', time: '19:30', venue: 'Kolkata' },
    { num: 66, home: 'Gujarat Titans',            away: 'Chennai Super Kings',       date: '2026-05-21', time: '19:30', venue: 'Ahmedabad' },
    { num: 67, home: 'Sunrisers Hyderabad',       away: 'Royal Challengers Bengaluru', date: '2026-05-22', time: '19:30', venue: 'Hyderabad' },
    { num: 68, home: 'Lucknow Super Giants',      away: 'Punjab Kings',              date: '2026-05-23', time: '19:30', venue: 'Lucknow' },
    { num: 69, home: 'Mumbai Indians',            away: 'Rajasthan Royals',          date: '2026-05-24', time: '15:30', venue: 'Mumbai' },
    { num: 70, home: 'Kolkata Knight Riders',     away: 'Delhi Capitals',            date: '2026-05-24', time: '19:30', venue: 'Kolkata' }
  ]
};